### ISSUE TITLE
Is it possible to use something like a loop for trials repetition in a folder ?

### ISSUE THREAD

**Issue by IvaneNuel** [avosskuehler/ogama#2]
Hello, 

I am novice with OGAMA and I would like to know if it was possible to use something like a loop to repeat trials of one folder (instead of cretaing multiple folder with the same slides inside).
In my experiment, I want to randomly present each of the two groups of slides ("Induction_Evitement_J" and "Induction_Evitement_V") and to repeat this presentation X times.

This is the structure that I have:

![sans titre](https://user-images.githubusercontent.com/33624832/32723920-8eeeea62-c86f-11e7-84fc-efcb3c72ecb5.png)
 
Is this kind of option possible in OGAMA ?

Thank you in advance for any help,

Have a good day,

Ivane

**Comment by avosskuehler** [comment]
Hi Ivane,
this feature is not implemented, sorry. But you can adapt the sources so that it suits your needs, Ogama is open source ...
The only thing I can think of without touching the sources is a kind of workaround using a link slide, which links to the start of the trial again, when reaching the end of the two groups block. The repetition factor X must be directed manually from the controller.
Regards, Adrian
